
services:

  WASA-API:
    image: wasaapi
    container_name: wasaapi
    build: WASA-API
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      
  Nginx:
    image: nginx
    container_name: nginx
    build: Nginx
    ports:
      - 443:443